/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SocialRefRouteImport } from './routes/social-ref'
import { Route as SocialCareRouteImport } from './routes/social-care'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as EmergRouteImport } from './routes/emerg'
import { Route as DispoRouteImport } from './routes/dispo'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppIntakePsychiatryRouteImport } from './routes/app/intake/psychiatry'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRefRoute = SocialRefRouteImport.update({
  id: '/social-ref',
  path: '/social-ref',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialCareRoute = SocialCareRouteImport.update({
  id: '/social-care',
  path: '/social-care',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergRoute = EmergRouteImport.update({
  id: '/emerg',
  path: '/emerg',
  getParentRoute: () => rootRouteImport,
} as any)
const DispoRoute = DispoRouteImport.update({
  id: '/dispo',
  path: '/dispo',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIntakePsychiatryRoute = AppIntakePsychiatryRouteImport.update({
  id: '/app/intake/psychiatry',
  path: '/app/intake/psychiatry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/directory': typeof DirectoryRoute
  '/dispo': typeof DispoRoute
  '/emerg': typeof EmergRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/reference': typeof ReferenceRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/social-care': typeof SocialCareRoute
  '/social-ref': typeof SocialRefRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/workflow': typeof WorkflowRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/intake/psychiatry': typeof AppIntakePsychiatryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/directory': typeof DirectoryRoute
  '/dispo': typeof DispoRoute
  '/emerg': typeof EmergRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/reference': typeof ReferenceRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/social-care': typeof SocialCareRoute
  '/social-ref': typeof SocialRefRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/workflow': typeof WorkflowRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/intake/psychiatry': typeof AppIntakePsychiatryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/directory': typeof DirectoryRoute
  '/dispo': typeof DispoRoute
  '/emerg': typeof EmergRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/reference': typeof ReferenceRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/social-care': typeof SocialCareRoute
  '/social-ref': typeof SocialRefRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/workflow': typeof WorkflowRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/intake/psychiatry': typeof AppIntakePsychiatryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/directory'
    | '/dispo'
    | '/emerg'
    | '/plans'
    | '/privacy'
    | '/reference'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/social-care'
    | '/social-ref'
    | '/terms'
    | '/trust'
    | '/workflow'
    | '/auth/callback'
    | '/app/intake/psychiatry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/directory'
    | '/dispo'
    | '/emerg'
    | '/plans'
    | '/privacy'
    | '/reference'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/social-care'
    | '/social-ref'
    | '/terms'
    | '/trust'
    | '/workflow'
    | '/auth/callback'
    | '/app/intake/psychiatry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/directory'
    | '/dispo'
    | '/emerg'
    | '/plans'
    | '/privacy'
    | '/reference'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/social-care'
    | '/social-ref'
    | '/terms'
    | '/trust'
    | '/workflow'
    | '/auth/callback'
    | '/app/intake/psychiatry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  DirectoryRoute: typeof DirectoryRoute
  DispoRoute: typeof DispoRoute
  EmergRoute: typeof EmergRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferenceRoute: typeof ReferenceRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SocialCareRoute: typeof SocialCareRoute
  SocialRefRoute: typeof SocialRefRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  WorkflowRoute: typeof WorkflowRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AppIntakePsychiatryRoute: typeof AppIntakePsychiatryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-ref': {
      id: '/social-ref'
      path: '/social-ref'
      fullPath: '/social-ref'
      preLoaderRoute: typeof SocialRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-care': {
      id: '/social-care'
      path: '/social-care'
      fullPath: '/social-care'
      preLoaderRoute: typeof SocialCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emerg': {
      id: '/emerg'
      path: '/emerg'
      fullPath: '/emerg'
      preLoaderRoute: typeof EmergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispo': {
      id: '/dispo'
      path: '/dispo'
      fullPath: '/dispo'
      preLoaderRoute: typeof DispoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/intake/psychiatry': {
      id: '/app/intake/psychiatry'
      path: '/app/intake/psychiatry'
      fullPath: '/app/intake/psychiatry'
      preLoaderRoute: typeof AppIntakePsychiatryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  DirectoryRoute: DirectoryRoute,
  DispoRoute: DispoRoute,
  EmergRoute: EmergRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ReferenceRoute: ReferenceRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SocialCareRoute: SocialCareRoute,
  SocialRefRoute: SocialRefRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  WorkflowRoute: WorkflowRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AppIntakePsychiatryRoute: AppIntakePsychiatryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
